[package]
authors = ["Baqar Hassan <baqar.hassan92@gmail.com>"]
edition = "2018"
name = "usart"
version = "0.0.1"

[dependencies]
aux11 = { path = "auxiliary" }

[dependencies.heapless]
default-features = false
version = "0.3.7"
